import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { formatCents } from "@/lib/money";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#666", marginBottom: 16 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: "#ddd" },
  header: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: "#000", fontWeight: 700 },
  section: { marginTop: 18 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginBottom: 8 },
  totalRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#000", fontWeight: 700, fontSize: 13 },
});

export interface ReceiptPdfProps {
  groupName: string;
  description: string;
  occurredOn: string;
  items: { item_name: string; quantity: number; unit_price_cents: number }[];
  subtotalCents: number;
  taxCents: number;
  tipCents: number;
  discountCents: number;
  totalCents: number;
  perPerson: { name: string; cents: number }[];
}

export function ReceiptDocument(props: ReceiptPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{props.description}</Text>
        <Text style={styles.subtitle}>
          {props.groupName} · {props.occurredOn} · Generated by LEDGR
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Items</Text>
          <View style={styles.header}>
            <Text style={{ flex: 2 }}>Item</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>Qty</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>Unit</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>Line total</Text>
          </View>
          {props.items.map((it, i) => (
            <View key={i} style={styles.row}>
              <Text style={{ flex: 2 }}>{it.item_name}</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>{it.quantity}</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>{formatCents(it.unit_price_cents)}</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>{formatCents(Math.round(it.quantity * it.unit_price_cents))}</Text>
            </View>
          ))}
          <View style={styles.row}>
            <Text style={{ flex: 3 }}>Subtotal</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>{formatCents(props.subtotalCents)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={{ flex: 3 }}>Tax</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>{formatCents(props.taxCents)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={{ flex: 3 }}>Tip</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>{formatCents(props.tipCents)}</Text>
          </View>
          {props.discountCents > 0 && (
            <View style={styles.row}>
              <Text style={{ flex: 3 }}>Discount</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>-{formatCents(props.discountCents)}</Text>
            </View>
          )}
          <View style={styles.totalRow}>
            <Text>Total</Text>
            <Text>{formatCents(props.totalCents)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Per-person breakdown</Text>
          {props.perPerson.map((p, i) => (
            <View key={i} style={styles.row}>
              <Text>{p.name}</Text>
              <Text>{formatCents(p.cents)}</Text>
            </View>
          ))}
        </View>

        <Text style={{ marginTop: 24, fontSize: 9, color: "#888" }}>
          This is a bookkeeping record only. Settling a debt in LEDGR does not move real money — payment happens
          outside the app.
        </Text>
      </Page>
    </Document>
  );
}
