/**
 * Assignment 3 — JMeter session capture.
 *
 * Ledgr authenticates through `@supabase/ssr`: the browser client performs
 * the password grant against the Supabase Auth server and then writes the
 * session into a chunked `sb-<ref>-auth-token` cookie that every server
 * component and route handler reads. JMeter cannot execute JavaScript, so
 * it cannot perform that sign-in itself — a JMeter thread hitting
 * `/dashboard` without a cookie is simply redirected to `/sign-in` and
 * would measure the login page instead of the application.
 *
 * This script drives a real headless Chromium sign-in once, then writes the
 * resulting cookie header to a JMeter properties file that the test plan
 * loads through `${__P(ledgr.cookie)}`. The load test therefore exercises
 * the authenticated request path (session validation, RLS-scoped queries,
 * real page renders) rather than an anonymous redirect.
 *
 * It also records every JavaScript bundle the authenticated pages fetch, so
 * the test plan can target the real hashed bundle URLs the assignment asks
 * for instead of guessed filenames.
 *
 * Usage: npm run capture:session -- --base-url http://localhost:3100
 */
import { chromium } from "@playwright/test";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const args = process.argv.slice(2);
function arg(name: string, fallback: string): string {
  const index = args.indexOf(`--${name}`);
  return index !== -1 && args[index + 1] ? args[index + 1] : fallback;
}

const BASE_URL = arg("base-url", "http://localhost:3100");
const EMAIL = arg("email", "demo@ledgr.app");
const PASSWORD = arg("password", "DemoPass123!");
const OUT_DIR = resolve(__dirname, "..", "jmeter");

const PAGES = ["/dashboard", "/ledger", "/analytics"];

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  const bundles = new Map<string, Set<string>>();
  page.on("response", (response) => {
    const url = new URL(response.url());
    if (url.origin !== new URL(BASE_URL).origin) return;
    if (!url.pathname.endsWith(".js")) return;
    const current = page.url();
    const key = PAGES.find((p) => current.includes(p)) ?? "/sign-in";
    if (!bundles.has(key)) bundles.set(key, new Set());
    bundles.get(key)!.add(url.pathname);
  });

  console.log(`Signing in to ${BASE_URL} as ${EMAIL} ...`);
  await page.goto(`${BASE_URL}/sign-in`, { waitUntil: "networkidle" });
  await page.locator('input[type="email"]').fill(EMAIL);
  await page.locator('input[type="password"]').fill(PASSWORD);
  await page.locator('button[type="submit"]').click();
  await page.waitForURL(/\/dashboard/, { timeout: 30_000 });
  console.log("Signed in — landed on /dashboard.");

  for (const path of PAGES) {
    await page.goto(`${BASE_URL}${path}`, { waitUntil: "networkidle" });
    console.log(`  visited ${path}`);
  }

  const cookies = await context.cookies();
  const appCookies = cookies.filter((c) => c.name.startsWith("sb-"));
  if (appCookies.length === 0) {
    throw new Error("No Supabase auth cookies found — sign-in did not establish a session.");
  }
  const cookieHeader = appCookies.map((c) => `${c.name}=${c.value}`).join("; ");

  // JMeter property files are plain `key=value`; the cookie value contains
  // no newline so a single line is safe, but backslashes must be escaped
  // because java.util.Properties treats them as escape characters.
  const escaped = cookieHeader.replace(/\\/g, "\\\\");
  writeFileSync(
    resolve(OUT_DIR, "session.properties"),
    [
      "# Generated by `npm run capture:session` — DO NOT COMMIT.",
      "# Regenerate before each JMeter run; the Supabase access token expires in 1 hour.",
      `ledgr.baseurl=${BASE_URL}`,
      `ledgr.cookie=${escaped}`,
      "",
    ].join("\n"),
    "utf8"
  );
  console.log(`Wrote ${appCookies.length} cookie(s) to assignment3/jmeter/session.properties`);

  const bundleReport: Record<string, string[]> = {};
  for (const [route, set] of bundles) bundleReport[route] = [...set].sort();
  writeFileSync(resolve(OUT_DIR, "bundles.json"), JSON.stringify(bundleReport, null, 2) + "\n", "utf8");

  console.log("\nJavaScript bundles observed per route:");
  for (const [route, paths] of Object.entries(bundleReport)) {
    console.log(`  ${route}: ${paths.length} files`);
    for (const p of paths) console.log(`      ${p}`);
  }

  await browser.close();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
